eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        ## service1
        - id: biometric-service
          uri: lb://biometric-service
          predicates:
            - Path=/employee/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: biometric-service
                fallbackuri: forward:/biometricFallback
        ## service2
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/attendance/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: attendance-service
                fallbackuri: forward:/attendanceFallback
        ## auth-service
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authorization-service
                fallbackuri: forward:/authorizationFallback

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: hystirx.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000